* [exmpl]: fix compile bug
The C++ compiler in openSUSE factory tries to use a operator, which is
completely non wanted. Putting some space between the macro and the
quote sign fixes the compile warning:
error: unable to find string literal operator 'operator"" XCM_COLOR_DESKTOP'